API v0.20.0: switch to ingress API version to GA v1 from v1beta1
wbstack/charts pull request #105
Opened 2022-10-28 13:47 UTC by deer-wmde

same procedure as in #104

2022-11-01 18:51 UTC, rosalieper approved these changes
LGTM

2022-11-03 14:50 UTC, dati18 requested changes
I think you also have to update api image version to `8x.9.8` in `values.yaml` file

2022-11-04 11:05 UTC, rosalieper commented
> I think you also have to update api image version to `8x.9.8` in `values.yaml` file

Hi, I think since we are creating an new chart version the api image version does not need a change. There was no change in the api component. My assumption is that it is good as is.

2022-11-07 09:43 UTC, dati18 approved these changes

2022-11-07 11:04 UTC, merged