replace NodePort with ClusterIP
wbstack/charts pull request #35
Opened 2021-11-17 13:27 UTC by dati18

Replace NodePort with ClusterIP

2021-11-19 09:07 UTC, deer-wmde requested changes
I tested it in my local cluster and it seems to work! :partying_face: 

But I noticed there are still some charts with NodePort:
- tool-widar
- tool-quickstatements
- tool-cradle
- ui

2021-11-19 09:59 UTC, dati18 commented
> I tested it in my local cluster and it seems to work! partying_face
> 
> But I noticed there are still some charts with NodePort:
> 
> * tool-widar
> * tool-quickstatements
> * tool-cradle
> * ui

sure, lemme check that...

2021-11-19 12:35 UTC, dati18 commented
> I tested it in my local cluster and it seems to work! partying_face
> 
> But I noticed there are still some charts with NodePort:
> 
> * tool-widar
> * tool-quickstatements
> * tool-cradle
> * ui

I remember I didn't change them because there are a few errors. I have fixed most of it...

2021-11-19 13:40 UTC, deer-wmde approved these changes

2021-11-24 19:17 UTC, addshore requested changes

2021-11-24 19:17 UTC, addshore commented on charts/api/README.md
> +- 0.10.1: Change service from `NodePort` to `ClusterIP`
```suggestion
- 0.10.2: Change service from `NodePort` to `ClusterIP`
```

2021-11-26 13:17 UTC, addshore approved these changes

2021-11-26 13:17 UTC, merged